"""add account_type to instagram_profiles

Revision ID: 1ea512d17310
Revises: remove_is_primary_001
Create Date: 2026-02-16 20:10:37.985760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea512d17310'
down_revision: Union[str, None] = 'remove_is_primary_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_profiles', sa.Column('account_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_profiles', 'account_type')
    # ### end Alembic commands ###
