"""add account_type to instagram_profiles

Revision ID: 1ea512d17310
Revises: remove_is_primary_001
Create Date: 2026-02-16 20:10:37.985760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ea512d17310'
down_revision: Union[str, None] = 'remove_is_primary_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # Check if instagram_profiles table exists (it may not on VPS if the DB
    # was reset after this model was added to models.py but before any
    # migration created the table -- the app's create_all() runs after Alembic)
    result = conn.execute(sa.text(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='instagram_profiles'"
    ))
    if not result.fetchone():
        # Create the full table (matches models.py definition)
        op.create_table(
            'instagram_profiles',
            sa.Column('sender_id', sa.String(50), primary_key=True),
            sa.Column('username', sa.String(100), nullable=True),
            sa.Column('profile_picture_url', sa.String(500), nullable=True),
            sa.Column('account_type', sa.String(20), nullable=True),
            sa.Column('last_updated', sa.DateTime(), nullable=False),
        )
        op.create_index('idx_profile_last_updated', 'instagram_profiles', ['last_updated'])
    else:
        # Table exists -- just add the new column
        op.add_column('instagram_profiles', sa.Column('account_type', sa.String(length=20), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_profiles', 'account_type')
    # ### end Alembic commands ###
