"""Initial schema

Revision ID: 248bd1781663
Revises: 
Create Date: 2025-11-02 23:48:37.487638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248bd1781663'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_business_accounts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('app_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('webhook_verify_token', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='accountstatusenum'), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_business_accounts_status'), 'instagram_business_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_instagram_business_accounts_username'), 'instagram_business_accounts', ['username'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('participant_id', sa.String(length=50), nullable=False),
    sa.Column('participant_username', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'BLOCKED', name='conversationstatusenum'), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_business_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_id', 'conversations', ['account_id'], unique=False)
    op.create_index('idx_last_message_at', 'conversations', ['last_message_at'], unique=False)
    op.create_index('idx_unique_account_participant', 'conversations', ['account_id', 'participant_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirectionenum'), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('recipient_id', sa.String(length=50), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_business_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_conversation', 'messages', ['account_id', 'conversation_id'], unique=False)
    op.create_index('idx_timestamp', 'messages', ['timestamp'], unique=False)
    op.create_table('response_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger_type', sa.Enum('KEYWORD', 'PATTERN', 'INTENT', name='triggertypeenum'), nullable=False),
    sa.Column('trigger_value', sa.Text(), nullable=False),
    sa.Column('response_template', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_business_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_account_active', 'response_rules', ['account_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_account_active', table_name='response_rules')
    op.drop_table('response_rules')
    op.drop_index('idx_timestamp', table_name='messages')
    op.drop_index('idx_account_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_unique_account_participant', table_name='conversations')
    op.drop_index('idx_last_message_at', table_name='conversations')
    op.drop_index('idx_account_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_instagram_business_accounts_username'), table_name='instagram_business_accounts')
    op.drop_index(op.f('ix_instagram_business_accounts_status'), table_name='instagram_business_accounts')
    op.drop_table('instagram_business_accounts')
    # ### end Alembic commands ###
