"""Make message_text nullable in crm_outbound_messages

Revision ID: 3f8c7729902f
Revises: 8f91b94b697c
Create Date: 2025-12-13 14:20:36.329200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8c7729902f'
down_revision: Union[str, None] = '8f91b94b697c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_outbound_messages', 'message_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index('idx_is_active', 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_is_active', table_name='users')
    op.alter_column('crm_outbound_messages', 'message_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
