"""add_oauth_multi_account_support

Revision ID: 4708f20f955c
Revises: 3f8c7729902f
Create Date: 2025-12-18 23:46:58.300336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4708f20f955c'
down_revision: Union[str, None] = '3f8c7729902f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    from sqlalchemy.exc import OperationalError

    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    # Create oauth_states table if it doesn't exist
    if 'oauth_states' not in existing_tables:
        op.create_table('oauth_states',
        sa.Column('state', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('redirect_uri', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('state')
        )
        op.create_index('idx_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
        op.create_index('idx_oauth_states_user_id', 'oauth_states', ['user_id'], unique=False)

    # Create user_accounts table if it doesn't exist
    if 'user_accounts' not in existing_tables:
        op.create_table('user_accounts',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account_id', sa.String(length=50), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=False),
        sa.Column('linked_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sqlite_autoincrement=True
        )
        op.create_index('idx_user_accounts_account_id', 'user_accounts', ['account_id'], unique=False)
        op.create_index('idx_user_accounts_user_id', 'user_accounts', ['user_id'], unique=False)
        op.create_index('idx_user_accounts_user_primary', 'user_accounts', ['user_id', 'is_primary'], unique=False)
    # Add new columns to accounts table if they don't exist
    accounts_columns = [col['name'] for col in inspector.get_columns('accounts')]
    if 'token_expires_at' not in accounts_columns:
        op.add_column('accounts', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    if 'refresh_token_encrypted' not in accounts_columns:
        op.add_column('accounts', sa.Column('refresh_token_encrypted', sa.Text(), nullable=True))
    if 'profile_picture_url' not in accounts_columns:
        op.add_column('accounts', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    if 'last_synced_at' not in accounts_columns:
        op.add_column('accounts', sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # Use batch operations for SQLite compatibility (alter nullable columns only)
    # Check if columns are already nullable to avoid re-running batch operation
    accounts_columns_detailed = {col['name']: col for col in inspector.get_columns('accounts')}
    crm_webhook_url_nullable = accounts_columns_detailed.get('crm_webhook_url', {}).get('nullable', True)
    webhook_secret_nullable = accounts_columns_detailed.get('webhook_secret', {}).get('nullable', True)

    # Only run batch operation if columns need to be made nullable
    if not (crm_webhook_url_nullable and webhook_secret_nullable):
        # Clean up any leftover temp tables from previous failed runs
        try:
            op.execute('DROP TABLE IF EXISTS _alembic_tmp_accounts')
        except:
            pass

        with op.batch_alter_table('accounts', schema=None) as batch_op:
            if not crm_webhook_url_nullable:
                batch_op.alter_column('crm_webhook_url',
                           existing_type=sa.VARCHAR(length=500),
                           nullable=True)
            if not webhook_secret_nullable:
                batch_op.alter_column('webhook_secret',
                           existing_type=sa.VARCHAR(length=100),
                           nullable=True)

    # Add index for token expiration if it doesn't exist
    accounts_indexes = [idx['name'] for idx in inspector.get_indexes('accounts')]
    if 'idx_token_expires_at' not in accounts_indexes:
        op.create_index('idx_token_expires_at', 'accounts', ['token_expires_at'], unique=False)

    # Add new columns to users table if they don't exist
    users_columns = [col['name'] for col in inspector.get_columns('users')]
    if 'oauth_provider' not in users_columns:
        op.add_column('users', sa.Column('oauth_provider', sa.String(length=50), nullable=True))
    if 'oauth_provider_id' not in users_columns:
        op.add_column('users', sa.Column('oauth_provider_id', sa.String(length=100), nullable=True))
    if 'oauth_email' not in users_columns:
        op.add_column('users', sa.Column('oauth_email', sa.String(length=255), nullable=True))

    # Create indexes for users if they don't exist
    users_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
    if 'idx_is_active' not in users_indexes:
        op.create_index('idx_is_active', 'users', ['is_active'], unique=False)
    if 'idx_oauth_provider' not in users_indexes:
        op.create_index('idx_oauth_provider', 'users', ['oauth_provider', 'oauth_provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.exc import OperationalError

    op.drop_index('idx_oauth_provider', table_name='users')

    # Try to drop idx_is_active (may not exist if created by earlier migration)
    try:
        op.drop_index('idx_is_active', table_name='users')
    except OperationalError:
        # Index might be from earlier migration or already dropped, skip
        pass

    op.drop_column('users', 'oauth_email')
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    # Drop index and columns (reverse of upgrade)
    op.drop_index('idx_token_expires_at', table_name='accounts')

    # Use batch operations for SQLite compatibility (alter nullable columns)
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('webhook_secret',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=False)
        batch_op.alter_column('crm_webhook_url',
                   existing_type=sa.VARCHAR(length=500),
                   nullable=False)

    # Drop added columns
    op.drop_column('accounts', 'last_synced_at')
    op.drop_column('accounts', 'profile_picture_url')
    op.drop_column('accounts', 'refresh_token_encrypted')
    op.drop_column('accounts', 'token_expires_at')
    op.drop_index('idx_user_accounts_user_primary', table_name='user_accounts')
    op.drop_index('idx_user_accounts_user_id', table_name='user_accounts')
    op.drop_index('idx_user_accounts_account_id', table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index('idx_oauth_states_user_id', table_name='oauth_states')
    op.drop_index('idx_oauth_states_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    # ### end Alembic commands ###
