"""Add CRM integration tables (accounts and outbound_messages)

Revision ID: 57fc6c6e6f58
Revises: c67fc6b5677b
Create Date: 2025-11-06 23:54:31.740914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fc6c6e6f58'
down_revision: Union[str, None] = 'c67fc6b5677b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('instagram_account_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('crm_webhook_url', sa.String(length=500), nullable=False),
    sa.Column('webhook_secret', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_account_id')
    )
    op.create_index('idx_instagram_account_id', 'accounts', ['instagram_account_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_account_status', 'outbound_messages', ['account_id', 'status'], unique=False)
    op.create_index('idx_idempotency_key', 'outbound_messages', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_idempotency_key', table_name='outbound_messages')
    op.drop_index('idx_account_status', table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index('idx_instagram_account_id', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
