"""add conversations_api_id to accounts

Revision ID: 5e1d9fb19837
Revises: 1ea512d17310
Create Date: 2026-02-17 02:10:29.519731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1d9fb19837'
down_revision: Union[str, None] = '1ea512d17310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()

    # Check if accounts table exists -- on VPS the DB may have been reset
    # after models.py was updated but before migrations ran. In that case
    # create_all() will create the table with the new column already present.
    result = conn.execute(sa.text(
        "SELECT name FROM sqlite_master WHERE type='table' AND name='accounts'"
    ))
    if not result.fetchone():
        return

    # Check if column already exists (idempotent)
    columns = [row[1] for row in conn.execute(sa.text("PRAGMA table_info('accounts')"))]
    if 'conversations_api_id' in columns:
        return

    op.add_column('accounts', sa.Column('conversations_api_id', sa.String(length=50), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'conversations_api_id')
    # ### end Alembic commands ###
