"""Add account_type and oauth_user_id tracking to accounts

Revision ID: 6b5301eac9d1
Revises: 054b11c44775
Create Date: 2025-12-21 13:34:05.030682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5301eac9d1'
down_revision: Union[str, None] = '054b11c44775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.String(length=20), nullable=True))
    op.add_column('accounts', sa.Column('oauth_user_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'oauth_user_id')
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
