"""add authentication tables (api_keys and api_key_permissions)

Revision ID: 7fabcd2fc75f
Revises: e75f64bf2da2
Create Date: 2025-11-17 21:46:21.306864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fabcd2fc75f'
down_revision: Union[str, None] = 'e75f64bf2da2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('key_prefix', sa.String(length=20), nullable=False),
        sa.Column('key_hash', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('type', sa.Enum('ADMIN', 'ACCOUNT', name='apikeytype'), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_index('idx_is_active', 'api_keys', ['is_active'], unique=False)

    op.create_table('api_key_permissions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('api_key_id', sa.String(length=50), nullable=False),
        sa.Column('account_id', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_key_id', 'api_key_permissions', ['api_key_id'], unique=False)
    op.create_index('idx_account_id', 'api_key_permissions', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_account_id', table_name='api_key_permissions')
    op.drop_index('idx_api_key_id', table_name='api_key_permissions')
    op.drop_table('api_key_permissions')

    op.drop_index('idx_is_active', table_name='api_keys')
    op.drop_index('idx_key_prefix', table_name='api_keys')
    op.drop_table('api_keys')

    # Drop enum type (for PostgreSQL/MySQL, no-op for SQLite)
    sa.Enum(name='apikeytype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
