"""add_media_attachments_support

Revision ID: 8f91b94b697c
Revises: d806d6558b2e
Create Date: 2025-12-11 23:43:41.280257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f91b94b697c'
down_revision: Union[str, None] = 'd806d6558b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create message_attachments table for media support
    op.create_table('message_attachments',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('attachment_index', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=False),
    sa.Column('media_url_local', sa.Text(), nullable=True),
    sa.Column('media_mime_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_attachments_media_type', 'message_attachments', ['media_type'], unique=False)
    op.create_index('idx_message_attachments_message_id', 'message_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop message_attachments table and indices
    op.drop_index('idx_message_attachments_message_id', table_name='message_attachments')
    op.drop_index('idx_message_attachments_media_type', table_name='message_attachments')
    op.drop_table('message_attachments')
    # ### end Alembic commands ###
