"""Simplified schema - messages only (YAGNI)

Revision ID: c67fc6b5677b
Revises: 
Create Date: 2025-11-03 00:15:31.546051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67fc6b5677b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=50), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_timestamp', 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timestamp', table_name='messages')
    op.drop_index('idx_sender', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
