"""add instagram_message_id and error fields to outbound_messages

Revision ID: e75f64bf2da2
Revises: 57fc6c6e6f58
Create Date: 2025-11-08 15:54:34.678769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75f64bf2da2'
down_revision: Union[str, None] = '57fc6c6e6f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_messages', sa.Column('instagram_message_id', sa.String(length=100), nullable=True))
    op.add_column('outbound_messages', sa.Column('error_code', sa.String(length=50), nullable=True))
    op.add_column('outbound_messages', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_messages', 'error_message')
    op.drop_column('outbound_messages', 'error_code')
    op.drop_column('outbound_messages', 'instagram_message_id')
    # ### end Alembic commands ###
